<a href="https://colab.research.google.com/github/inaafina/FinalThesis/blob/main/EDA_BPJS_1516.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 01Kepesertaan

## Open file

In [13]:
#connecting to the drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [16]:
# Read the CSV file with the specified delimiter
df_1 = pd.read_csv('/content/drive/MyDrive/**SEMESTER VII/4. Proposal/Code Related/BPJS 2015-2016/01Kepesertaan.csv', delimiter='|')

# Display the first few rows of the DataFrame
df_1.head()

,PSTV01,PSTV02,PSTV03,PSTV04,PSTV05,PSTV06,PSTV07,PSTV08,PSTV09,PSTV10,PSTV11,PSTV12,PSTV13,PSTV14,PSTV15
0,40691029,40691029,29sep1967,Peserta,Laki-laki,KAWIN,Kelas III,PBPU,SULAWESI TENGAH,KAB. POSO,Pem Kab,Puskesmas,SULAWESI TENGAH,KAB. POSO,31.515679
1,152493455,3033115,01jun1999,Anak,Perempuan,TIDAK TERDEFENISI,Kelas III,PBI APBN,GORONTALO,KAB. BONE BOLANGO,Pem Kab,Puskesmas,GORONTALO,KAB. BONE BOLANGO,93.601568
2,186237297,186237297,23jan1979,Peserta,Laki-laki,KAWIN,Kelas III,PBPU,JAWA TIMUR,KAB. MOJOKERTO,Pem Kab,Puskesmas,JAWA TIMUR,KAB. MOJOKERTO,451.724740
3,41208383,115992342,17sep2007,Anak,Laki-laki,BELUM KAWIN,Kelas I,PPU,NANGGROE ACEH DARUSSALAM,KOTA BANDA ACEH,Pem Kab,Puskesmas,NANGGROE ACEH DARUSSALAM,KAB. ACEH JAYA,199.704350
4,91535814,89186582,01oct2007,Anak,Laki-laki,TIDAK TERDEFENISI,Kelas III,PBI APBN,JAWA TENGAH,KAB. MAGELANG,Pem Kab,Puskesmas,JAWA TENGAH,KAB. MAGELANG,934.439890

In [20]:
df_1.nunique()

PSTV01    1697452
PSTV02     586969
PSTV03      33456
PSTV04          5
PSTV05          3
PSTV06          4
PSTV07          4
PSTV08          5
PSTV09         35
PSTV10        513
PSTV11          9
PSTV12          3
PSTV13         34
PSTV14        514
PSTV15       6778
dtype: int64

In [25]:
df_1['PSTV05'].unique()

array(['Laki-laki', 'Perempuan', 'Tidak terdefinisi'], dtype=object)

In [27]:
(df_1['PSTV05'] == 'Tidak terdefinisi').sum()

#will drop the non defined

2

In [22]:
df_1.shape

(1697452, 15)

## Data cleansing

In [19]:
#checking for null values
df_1.isnull().sum()

PSTV01       0
PSTV02       0
PSTV03       0
PSTV04       0
PSTV05       0
PSTV06    5373
PSTV07       0
PSTV08       0
PSTV09     190
PSTV10     190
PSTV11    1389
PSTV12       0
PSTV13       2
PSTV14       2
PSTV15       0
dtype: int64

# 02KunjunganFKTP

## Open File

In [28]:
# Read the CSV file with the specified delimiter
df_2 = pd.read_csv('/content/drive/MyDrive/**SEMESTER VII/4. Proposal/Code Related/BPJS 2015-2016/02KunjunganFKTP.csv', delimiter='|')

# Display the first few rows of the DataFrame
df_2.head()

,PSTV01,FKP02,FKP03,FKP04,FKP05,FKP06,FKP07,FKP08,FKP09,FKP10,...,FKP15,FKP16,FKP17,FKP18,FKP19,FKP20,FKP21,FKP22,FKP23,PSTV15
0,218,214050216Y000058,24feb2016,24feb2016,LAMPUNG,KAB. LAMPUNG BARAT,Swasta,Dokter Umum,Dokter Praktek Perorangan,Rawat Jalan Tingkat Pratama,...,"Gastritis, unspecified",NaN,NaN,NaN,NaN,NaN,NaN,Kunjungan sakit,K29 Gastritis and duodenitis,22.901394
1,218,214050315Y000005,02mar2015,02mar2015,LAMPUNG,KAB. LAMPUNG BARAT,Swasta,Dokter Umum,Dokter Praktek Perorangan,Rawat Jalan Tingkat Pratama,...,Essential (primary) hypertension,NaN,NaN,NaN,NaN,NaN,NaN,Kunjungan sakit,I10 Essential (primary) hypertension,22.901394
2,340,115641115Y001030,20nov2015,20nov2015,JAWA TENGAH,KAB. SUKOHARJO,Swasta,Klinik Pratama,Klinik Non Rawat Inap,Rawat Jalan Tingkat Pratama,...,"Malignant neoplasm of colon, unspecified",JAWA TENGAH,KOTA SURAKARTA,Swasta,Rumah sakit,RS Swasta Setara Type C,INT,Kunjungan sakit,C18 Malignant neoplasm of colon,8.719338
3,340,78800516Y000637,26may2016,26may2016,JAWA TENGAH,KAB. SUKOHARJO,Swasta,Klinik Pratama,Klinik Non Rawat Inap,Rawat Jalan Tingkat Pratama,...,Myalgia,NaN,NaN,NaN,NaN,NaN,NaN,Kunjungan sakit,"M79 Other soft tissue disorders, not elsewhere...",8.719338
4,340,115641015Y000805,15oct2015,15oct2015,JAWA TENGAH,KAB. SUKOHARJO,Swasta,Klinik Pratama,Klinik Non Rawat Inap,Rawat Jalan Tingkat Pratama,...,"Acute bronchitis, unspecified",JAWA TENGAH,KOTA SURAKARTA,Pem Prov,Klinik Utama,Khusus Paru,PAR,Kunjungan sakit,J20 Acute bronchitis,8.719338

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_0, *['PSTV01'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_1, *['PSTV15'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_2, *['FKP02'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_3, *['FKP03'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_4, *['FKP04'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_5, *['FKP05'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plot(df, x_colname, y_colname, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(6 * figscale, 6 * figscale))
  df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha)
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plot(_df_6, *['PSTV01', 'PSTV15'], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(_df_7, *['PSTV01', 'PSTV15', 'FKP02'], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(_df_8, *['PSTV01', 'PSTV15', 'FKP03'], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(_df_9, *['PSTV01', 'PSTV15', 'FKP04'], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(_df_10, *['PSTV01', 'PSTV15', 'FKP05'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_11, *['PSTV01'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_12, *['PSTV15'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_13, *['FKP02', 'FKP03'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_14, *['FKP03', 'FKP04'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_15, *['FKP04', 'FKP05'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_16, *['FKP05', 'FKP06'], **{})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_17, *['PSTV01', 'FKP02'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_18, *['PSTV01', 'FKP03'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_19, *['PSTV01', 'FKP04'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_20, *['PSTV01', 'FKP05'], **{'inner': 'stick'})
chart

In [31]:
df_2.nunique()

PSTV01     465017
FKP02     1733757
FKP03         731
FKP04         766
FKP05          34
FKP06         510
FKP07           9
FKP08           6
FKP09          11
FKP10           3
FKP11          13
FKP12           5
FKP13           7
FKP14        8684
FKP15        8641
FKP16          35
FKP17         460
FKP18           9
FKP19           8
FKP20          38
FKP21          82
FKP22           2
FKP23        1818
PSTV15       3556
dtype: int64

In [29]:
#checking for null values
df_2.isnull().sum()

PSTV01          0
FKP02           0
FKP03           0
FKP04           2
FKP05           0
FKP06           0
FKP07          23
FKP08           0
FKP09           0
FKP10           0
FKP11           0
FKP12         772
FKP13           2
FKP14           2
FKP15       21004
FKP16     1572314
FKP17     1572314
FKP18     1572386
FKP19     1572316
FKP20     1572713
FKP21     1572324
FKP22           0
FKP23        4399
PSTV15          0
dtype: int64